title change admin password for a server
participant client
participant nova_api


# nova/api/compute/admin_password.py 
client->nova_api: changePassword
activate client
activate nova_api

# nova/api/openstack/compute/servers.py _action_create_image()
note over nova_api: validation schema
note over nova_api: authorize context
note over nova_api: get instance by uuid
note over nova_api: check policy
note over nova_api: check instance lock
note over nova_api: check instance cell
note over nova_api: ensure instance state is ACTIVE
nova_api->database: task_state = UPDATING_PASSWORD
database->nova_api: done
note over nova_api: record change password action
nova_api->nova_compute: set_admin_password
activate nova_compute
opt new password is None
    note over nova_compute: generate a random password
end
alt if current power state is not RUNNING
    nova_compute->database: task_state = None
    database->nova_api: done
    note over nova_compute: raise instance is not running exception
    nova_compute->nova_api: raise exception.InstancePasswordSetFailed
end
nova_compute->libvirt: set_admin_password
activate libvirt
alt virt type is not in (kvm, qemu)
    libvirt->nova_compute: raise exception.SetAdminPasswdNotSupported
end

alt 'hw_qemu_guest_agent' not in image properties
    libvirt->nova_compute: raise exception.QemuGuestAgentNotEnabled
end

note over libvirt: get os admin user from image properties\n or set default
note over libvirt: call guest.set_password()
libvirt->nova_compute: done
deactivate libvirt
note over nova_compute: update task state
nova_compute->database: task_state=None
database->nova_compute: done
nova_compute->nova_api: response
deactivate nova_compute
nova_api->client: response
deactivate nova_api
deactivate client
