title lock an instance(admin)

participant client
participant nova_api
participant database
#nova/api/openstack/compute/lock_server.py _lock()
client->nova_api:lock
activate nova_api
activate client
note over nova_api:get context
note over nova_api:authorize action 'lock' policy
note over nova_api:fetch instance,handling error checking

#nova/compute/api.py lock()
note over nova_api:check policy
note over nova_api:call lock()
nova_api->database:query instance.locked
activate database
database->nova_api:done
deactivate database
alt if instance is locked
nova_api->client:response
else if instance is not locked
nova_api->nova_api:update context
activate database
nova_api->database:update locked = true
nova_api->database:update owner
note over database:save()
end
deactivate nova_api
deactivate client
