title reset the state of a server

participant client
participant nova_api
participant database

client->nova_api: os-resetState
activate client
activate nova_api

# nova/api/openstack/compute/legacy_v2/contrib/admin_actions.py _reset_network()
note over nova_api: valid schema
note over nova_api: authrize context
nova_api->database: get instance by uuid
database->nova_api: done
nova_api->+database: vm_state = newState\ntask_state=None
database->nova_api: done
deactivate database
nova_api->client: response
deactivate nova_api
deactivate client
