title unlock an instance

participant client
participant nova_api
participant database
#nova/api/openstack/compute/lock_server.py _unlock()
client->nova_api:unlock
activate nova_api
activate client
note over nova_api:get context
note over nova_api:authorize action 'unlock' policy

nova_api->database: get instance by id
activate database
database->nova_api: done
deactivate database

#nova/compute/api.py unlock()
note over nova_api:check policy
nova_api->database:query instance.locked
activate database
database->nova_api:done
deactivate database

nova_api->database:instance.locked = False\nlocked_by=None
activate database
database->nova_api: done
deactivate database
nova_api->client: response
deactivate nova_api
deactivate client
