title unlock an instance

participant client
participant nova_api
participant database
#nova/api/openstack/compute/lock_server.py _unlock()
client->nova_api:unlock
activate nova_api
activate client
note over nova_api:get context
note over nova_api:authorize action 'unlock' policy
note over nova_api:fetch instance,handling error checking

#nova/compute/api.py unlock()
note over nova_api:check policy
note over nova_api:call unlock()
nova_api->database:query instance.locked
activate database
database->nova_api:done
deactivate database
alt if skip_policy_check and is_expected_locked_by are false
note over nova_api:check policy
else if skip_policy_check and is_expected_locked_by are true
nova_api->nova_api:update context
activate database
nova_api->database:update locked = False
nova_api->database:update locked_by = None
note over database:save()
end
deactivate nova_api
deactivate client
